<?php

/**
 * File: email_templates.php.
 * Author: Ulrich Block
 * Date: 25.05.15
 * Contact: <ulrich.block@easy-wi.com>
 *
 * This file is part of Easy-WI.
 *
 * Easy-WI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Easy-WI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Easy-WI.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Diese Datei ist Teil von Easy-WI.
 *
 * Easy-WI ist Freie Software: Sie koennen es unter den Bedingungen
 * der GNU General Public License, wie von der Free Software Foundation,
 * Version 3 der Lizenz oder (nach Ihrer Wahl) jeder spaeteren
 * veroeffentlichten Version, weiterverbreiten und/oder modifizieren.
 *
 * Easy-WI wird in der Hoffnung, dass es nuetzlich sein wird, aber
 * OHNE JEDE GEWAEHELEISTUNG, bereitgestellt; sogar ohne die implizite
 * Gewaehrleistung der MARKTFAEHIGKEIT oder EIGNUNG FUER EINEN BESTIMMTEN ZWECK.
 * Siehe die GNU General Public License fuer weitere Details.
 *
 * Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
 * Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.
 */


$emailTemplates = array(
    'emailbackup' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailbackup','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3%</p>\r\n    <p>%text4%</p>\r\n    <p>%text5%</p>\r\n    <p>%text6%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailbackup', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Sicherung des Servers</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>die Sicherung Ihres Servers</text1>\r\n	<text2>wurde um</text2>\r\n	<text3>fertig gestellt.</text3>\r\n	<text4>Ihr Server sollte weiterhin erreichbar sein.</text4>\r\n	<text5>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text5>\r\n	<text6>Die entsprechende Nummer finden Sie im Panel.</text6>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailbackup', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Your Serverbackup</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>the backup for your server</text1>\r\n	<text2>was created at</text2>\r\n	<text3>.</text3>\r\n	<text4>Your server should be still available for access.</text4>\r\n	<text5>If you have any questions feel free to use our supportsystem or give us a call.</text5>\r\n	<text6>You will find the phonenumber in our panel.</text6>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailbackuprestore' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailbackuprestore','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3%</p>\r\n    <p>%text4%</p>\r\n    <p>%text5%</p>\r\n    <p>%text6%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailbackuprestore', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Wiederherstellung Ihres Backups</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>das Backup Ihres Servers</text1>\r\n	<text2>wurde um</text2>\r\n	<text3>erfolgreich eingespielt.</text3>\r\n	<text4>Ihr Server sollte weiterhin erreichbar sein.</text4>\r\n	<text5>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text5>\r\n	<text6>Die entsprechende Nummer finden Sie im Panel.</text6>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailbackuprestore', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Your Serverbackup</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>the backup for your server</text1>\r\n	<text2>was successfully restored</text2>\r\n	<text3>.</text3>\r\n	<text4>Your server should be still available for access.</text4>\r\n	<text5>If you have any questions feel free to use our supportsystem or give us a call.</text5>\r\n	<text6>You will find the phonenumber in our panel.</text6>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emaildown' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emaildown','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3%</p>\r\n    <p>%text4%</p>\r\n    <p>%text5%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emaildown', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Server nicht erreichbar</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Ihr Servers</text1>\r\n	<text2>kann seit</text2>\r\n	<text3>nicht mehr erreicht werden.</text3>\r\n	<text4>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text4>\r\n	<text5>Die entsprechende Nummer finden Sie im Panel.</text5>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emaildown', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Server could not been reached</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>Your server</text1>\r\n	<text2>could not been reached since</text2>\r\n	<text3>.</text3>\r\n	<text4>If you have any questions feel free to use our supportsystem or give us a call.</text4>\r\n	<text5>You will find the phonenumber in our panel.</text5>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emaildownrestart' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emaildownrestart','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3%</p>\r\n    <p>%text4%</p>\r\n    <p>%text5%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emaildownrestart', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Server abgest&uuml;zt</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Ihr Servers</text1>\r\n	<text2>konnte am</text2>\r\n	<text3>nicht erreicht werden und wurde neu gstartet.</text3>\r\n	<text4>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text4>\r\n	<text5>Die entsprechende Nummer finden Sie im Panel.</text5>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emaildownrestart', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Server crashed</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>Your server</text1>\r\n	<text2>could not been reached at</text2>\r\n	<text3>and was restarted.</text3>\r\n	<text4>If you have any questions feel free to use our supportsystem or give us a call.</text4>\r\n	<text5>You will find the phonenumber in our panel.</text5>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailgserverupdate' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailgserverupdate','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3% %text4%</p>\r\n    <p>%text5%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailgserverupdate', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Update eines Masterservers</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Ein Gameserverupdate wurde beim Server</text1>\r\n	<text2>um</text2>\r\n	<text3>f&uuml;r das Spiel</text3> \r\n	<text4>fertig gestellt.</text4>\r\n	<text5>Ihre Server sollten weiterhin erreichbar sein.</text5>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailgserverupdate', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Masterservers has been updated</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>a gameserverupdate for the server</text1>\r\n	<text2>was applied at</text2>\r\n	<text3>for the game</text3> \r\n	<text4>.</text4>\r\n	<text5>Your server should be still available for access.</text5>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailnewticket' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailnewticket','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %date%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailnewticket', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Ticket</topic>\r\n	<text1>schrieb am</text1>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailnewticket', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Ticket</topic>\r\n	<text1>wrote at</text1>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailpwrecovery' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailpwrecovery','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1%</p>\r\n    <p>%server%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailpwrecovery', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Passwort Recovery</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Um ein neues Passwort anzufordern, rufen Sie bitte folgenden Best&auml;tigungslink auf:</text1>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailpwrecovery', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Password recovery</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>To require a new password please use following activation link:</text1>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailregister' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailregister','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1%</p>\r\n    <p>%server%</p>\r\n    <p>%text2%</p>\r\n    <p>%text3%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailregister', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Account Aktivierung</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>bitte aktivieren Sie Ihren Account indem sie auf folgenden Link klicken:</text1>\r\n	<text2>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text2>\r\n	<text3>Die entsprechende Nummer finden Sie im Panel.</text3>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailregister', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Account Activation</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>please activate your account by clicking following link:</text1>\r\n	<text2>If you have any questions feel free to use our supportsystem or give us a call.</text2>\r\n	<text3>You will find the phonenumber in our panel.</text3>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailsecuritybreach' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailsecuritybreach','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %date% %text2% %server% %text3%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailsecuritybreach', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Manipulation am Server entdeckt</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Am</text1>\r\n	<text2>wurde am Server</text2>\r\n	<text3>eine unzul&auml;ssige Manipulation entdeckt:</text3> \r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailsecuritybreach', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Server manipulation detected</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>At</text1>\r\n	<text2>a illegal servermanipulation at the server</text2>\r\n	<text3>was detected:</text3> \r\n	<noreply>This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailserverinstall' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailserverinstall','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3%</p>\r\n    <p>%text4%: %shorten%</p>\r\n    <p>%text_ip%: %ip%</p>\r\n    <p>%text_ports%: %ports%</p>\r\n    <p>%text5%</p>\r\n    <p>%text6%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailserverinstall', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Serverdienst installiert</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Ihr Serverdienst mit der Adresse/dem Namen</text1>\r\n	<text2>wurde um</text2>\r\n	<text3>installiert</text3>\r\n	<text4>Installiert wurde(n)</text4>\r\n	<text5>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text5>\r\n	<text6>Die entsprechende Nummer finden Sie im Panel.</text6>\r\n	<text_ip>Die IP lautet</text_ip>\r\n	<text_ports>Die Portbelegung lautet</text_ports>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailserverinstall', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Service installed</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>Your service with the name/address</text1>\r\n	<text2>has been installed at</text2>\r\n	<text3></text3>\r\n	<text4>Installed was/were</text4>\r\n	<text5>If you have any questions feel free to use our supportsystem or give us a call.</text5>\r\n	<text6>You will find the phonenumber in our panel.</text6>\r\n	<text_ip>The IP is</text_ip>\r\n	<text_ports>Port usage is</text_ports>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailuseradd' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailuseradd','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %date% %text2%</p>\r\n    <p>%text3%</p>\r\n    <p>%text4% %username%</p>\r\n    <p>%text5% %shorten%</p>\r\n    <p>%text6%</p>\r\n    <p>%text7%</p>\r\n    <p>%text8%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailuseradd', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Zugangsdaten</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Ihr Account wurde um</text1>\r\n	<text2>f&uuml;r Sie bereit gestellt.</text2>\r\n	<text3>Ihre Zugangsdaten lauten wie folgt:</text3> \r\n	<text4>Benutzername:</text4>\r\n	<text5>Passwort:</text5>\r\n	<text6>Bitte speichern Sie die Zugangsdaten aus Sicherheitsgr&uuml;nden in einer verschl&uuml;sselten Datei und l&ouml;schen diese Email danach.</text6>\r\n	<text7>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text7>\r\n	<text8>Die entsprechende Nummer finden Sie im Panel.</text8>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailuseradd', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Access Data</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>Your account has been created at</text1>\r\n	<text2>for you.</text2>\r\n	<text3>Your access data is as follows:</text3> \r\n	<text4>User name:</text4>\r\n	<text5>Password:</text5>\r\n	<text6>Please change this initial access data as soon as possible and delete this mail.</text6>\r\n	<text7>If you have any questions feel free to use our supportsystem or give us a call.</text7>\r\n	<text8>You will find the phonenumber in our panel.</text8>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailvinstall' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailvinstall','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server% %text2% %date% %text3%</p>\r\n    <p>%text4% %server%</p>\r\n    <p>%text5% %shorten%</p>\r\n    <p>%text6%</p>\r\n    <p>%text7%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailvinstall', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Rescue System gestartet</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Das Rescue System ihres Servers mit der IP</text1>\r\n	<text2>wurde um</text2>\r\n	<text3>für Sie gestartet.</text3> \r\n	<text4>Das Passwort für den Root Account lautet:</text4>\r\n	<text5>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text5>\r\n	<text6>Die entsprechende Nummer finden Sie im Panel.</text6>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailvinstall', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Rescue system has been started</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>The rescue system for your server with the IP</text1>\r\n	<text2>was started at</text2>\r\n	<text3>.</text3> \r\n	<text4>The root password is:</text4>\r\n	<text5>If you have any questions feel free to use our supportsystem or give us a call.</text5>\r\n	<text6>You will find the phonenumber in our panel.</text6>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailvoicemasterold' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailvoicemasterold','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %server%%text2%.</p>\r\n    <p>%text3%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailvoicemasterold', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Teamspeak 3 Master Server ist veraltet</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>eine veraltete Version wurde an Ihrem Voice Master Server</text1>\r\n	<text2> festgestellt</text2>\r\n	<text3>Bitte aktualisieren sie schnellst möglich um eventuelle Sicherheitslücken zu schließen.</text3>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailvoicemasterold', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Teamspeak 3 Master Server is outdated</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>an outdated version has been detected at your voice master server</text1>\r\n	<text2></text2>\r\n	<text3>Please update as soon as possible in order to close possible security issues.</text3>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    ),
    'emailvrescue' => array(
        'html' => "INSERT INTO `settings_email` (`email_setting_name`,`email_setting_value`,`reseller_id`) VALUES ('emailvrescue','<!DOCTYPE html> \r\n<head>\r\n	<title>%topic%</title>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n</head>\r\n<body>\r\n<div id=\"card\">\r\n    <font face=\"arial,helvetica,verdana,tahoma\" size=\"3\"><strong>%topic% %server%</strong></font>\r\n    <p>%salutation% %username%,</p>\r\n    <p>%text1% %ip% %text2% %date% %text3%</p>\r\n    <p>%text4% %rpw%</p>\r\n    <p>%text5%</p>\r\n    <p>%text6%</p>\r\n    <p>%emailregards%</p>\r\n    <p>%noreply%</p>\r\n\r\n    %emailfooter%\r\n</div>\r\n</body>\r\n</html>\r\n<style>\r\n#card {\r\n	margin:0 auto;\r\n	width:100%;\r\n	height:100%;\r\n	padding:20px 20px;\r\n	position:relative;\r\n	border-radius:3px;\r\n	box-shadow:1px 1px 1px rgba(3, 3, 3, 0.35);\r\n	background: #f1f1f1;\r\n	background: -moz-linear-gradient(-45deg,  #f1f1f1 0%, #f6f6f6 13%, #ffffff 68%, #ffffff 99%);\r\n	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,#f1f1f1), color-stop(13%,#f6f6f6), color-stop(68%,#ffffff), color-stop(99%,#ffffff));\r\n	background: -webkit-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -o-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: -ms-linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);\r\n	background: linear-gradient(-45deg,  #f1f1f1 0%,#f6f6f6 13%,#ffffff 68%,#ffffff 99%);}\r\n</style>',?) ON DUPLICATE KEY UPDATE `email_setting_value`=VALUES(`email_setting_value`)",
        'languages' => array(
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'de', 'emailvrescue', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Rescue System gestartet</topic>\r\n	<salutation>Sehr geehrte(r)</salutation>\r\n	<text1>Das Rescue System ihres Servers mit der IP</text1>\r\n	<text2>wurde um</text2>\r\n	<text3>f&uuml;r Sie gestartet.</text3> \r\n	<text4>Das Passwort f&uuml;r den Root Account lautet:</text4>\r\n	<text5>Bei Fragen nutzen Sie bitte das Ticketsystem, oder nehmen telefonisch Kontakt auf.</text5>\r\n	<text6>Die entsprechende Nummer finden Sie im Panel.</text6>\r\n	<noreply>(Dies ist eine automatisch versendete E-Mail. Bitte antworten Sie nicht darauf, weil dieses E-Mail Konto nicht in der Lage ist, E-Mails zu empfangen.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)",
            "INSERT INTO `translations` (`type`,`lang`,`transID`,`text`,`resellerID`) VALUES ('em', 'uk', 'emailvrescue', '<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n<sprache>\r\n	<topic>Rescue system has been started</topic>\r\n	<salutation>Dear</salutation>\r\n	<text1>The rescue system for your server with the IP</text1>\r\n	<text2>was started at</text2>\r\n	<text3>.</text3> \r\n	<text4>The root password is:</text4>\r\n	<text5>If you have any questions feel free to use our supportsystem or give us a call.</text5>\r\n	<text6>You will find the phonenumber in our panel.</text6>\r\n	<noreply>(This is an automated mail. Please do not reply to it since the account is configured to send only.)</noreply>\r\n</sprache>', ?) ON DUPLICATE KEY UPDATE `text`=VALUES(`text`)"
        )
    )
);