<?php

/**
 * File: gameslist.php.
 * Author: Ulrich Block
 * Date: 11.12.13
 * Contact: <ulrich.block@easy-wi.com>
 *
 * This file is part of Easy-WI.
 *
 * Easy-WI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Easy-WI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Easy-WI.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Diese Datei ist Teil von Easy-WI.
 *
 * Easy-WI ist Freie Software: Sie koennen es unter den Bedingungen
 * der GNU General Public License, wie von der Free Software Foundation,
 * Version 3 der Lizenz oder (nach Ihrer Wahl) jeder spaeteren
 * veroeffentlichten Version, weiterverbreiten und/oder modifizieren.
 *
 * Easy-WI wird in der Hoffnung, dass es nuetzlich sein wird, aber
 * OHNE JEDE GEWAEHELEISTUNG, bereitgestellt; sogar ohne die implizite
 * Gewaehrleistung der MARKTFAEHIGKEIT oder EIGNUNG FUER EINEN BESTIMMTEN ZWECK.
 * Siehe die GNU General Public License fuer weitere Details.
 *
 * Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
 * Programm erhalten haben. Wenn nicht, siehe <http://www.gnu.org/licenses/>.
 */


$gameImages = array(
    array(
        ':steamgame' => 'S',
        ':appID' => 232330,
        ':updates' => 1,
        ':shorten' => 'css',
        ':description' => 'Counter-Strike: Source',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => '',
        ':modfolder' => 'cstrike',
        ':fps' => 67,
        ':slots' => 12,
        ':map' => 'de_dust2',
        ':cmd' => './%binary% -game cstrike -ip %ip% -port %port% -hostport %port% +maxplayers %slots% +map %map% +tv_port %tvport% +tv_maxclients 1 +clientport %port3%',
        ':modcmds' => null,
        ':tic' => '66',
        ':gameq' => 'css',
        ':gamemod' => 'N',
        ':gamemod2' => '',
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 4,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => 27017,
        ':portFour' => 27018,
        ':portFive' => 27019,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 90,
        ':updates' => 1,
        ':shorten' => 'cstrike',
        ':description' => 'Counter-Strike 1.6',
        ':gamebinary' => 'hlds_run',
        ':gamebinaryWin' => 'hlds.exe',
        ':binarydir' => null,
        ':modfolder' => 'cstrike',
        ':fps' => 100,
        ':slots' => 12,
        ':map' => 'de_dust',
        ':cmd' => './%binary% -game cstrike -ip %ip% -port %port% -sys_ticrate %tic% +maxplayers %slots% +map %map% +fps_max %fps%',
        ':modcmds' => null,
        ':tic' => 100,
        ':gameq' => 'cs16',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 90,
        ':updates' => 1,
        ':shorten' => 'czero',
        ':description' => 'Counter-Strike: Condition Zero',
        ':gamebinary' => 'hlds_run',
        ':gamebinaryWin' => 'hlds.exe',
        ':binarydir' => null,
        ':modfolder' => 'czero',
        ':fps' => 100,
        ':slots' => 12,
        ':map' => 'de_dust',
        ':cmd' => './%binary% -game cstrike -ip %ip% -port %port% -pingboost 2 +sys_ticrate %tic% +maxplayers %slots% +map %map% +fps_max %fps%',
        ':modcmds' => null,
        ':tic' => 100,
        ':gameq' => 'cscz',
        ':gamemod' => 'Y',
        ':gamemod2' => null,
        ':configs' => "server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 232290,
        ':updates' => 1,
        ':shorten' => 'dods',
        ':description' => 'Day of Defeat: Source',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => null,
        ':modfolder' => 'dod',
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'dod_anzio',
        ':cmd' => './%binary% -game dod -ip %ip% -port %port% -verify_all +maxplayers %slots% +map %map% +tv_port %tvport% +replay_port %port3%',
        ':modcmds' => null,
        ':tic' => 66,
        ':gameq' => 'dods',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => 27017,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'cod4',
        ':description' => 'Call of Duty 4',
        ':gamebinary' => 'cod4_lnxded',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => './%binary% +set dedicated 2 +exec dedicated.cfg +set fs_basepath %absolutepath%/ +set fs_homepath %absolutepath%/.callofduty4 +set net_ip %ip% +set net_port %port% +set sv_maxclients %slots% +map_rotate',
        ':modcmds' => "[PAM402 = default]\r\n+set fs_game mods/pam402\r\n\r\n[Punkbuster]\r\n+set sv_punkbuster 1",
        ':tic' => null,
        ':gameq' => 'cod4',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "main/dedicated.cfg\r\nmain/server.cfg",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'main/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 4020,
        ':updates' => 1,
        ':shorten' => 'gmod',
        ':description' => 'Garrysmod',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => '',
        ':modfolder' => 'garrysmod',
        ':fps' => null,
        ':slots' => 0,
        ':map' => 'gm_flatgrass',
        ':cmd' => './%binary% -game garrysmod -ip %ip% -port %port% -hostport %port% +maxplayers %slots% +map %map% +tv_port %tvport% +tv_maxclients 1 +clientport %port3%',
        ':modcmds' => "[Sandbox = default]\r\n+gamemode sandbox\r\n\r\n[Terrortown]\r\n+gamemode terrortown\r\n\r\n[Murder]\r\n+gamemode murder\r\n\r\n[Dark RP]\r\n+gamemode darkrp",
        ':tic' => null,
        ':gameq' => 'gmod',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full\r\ncfg/mount.cfg full\r\ncfg/banned_user.cfg full\r\ncfg/skill.cfg full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => 27017,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => '',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 510,
        ':updates' => 1,
        ':shorten' => 'left4dead',
        ':description' => 'Left 4 Dead',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => '',
        ':modfolder' => 'l4d',
        ':fps' => null,
        ':slots' => 0,
        ':map' => 'l4d_airport01_greenhouse',
        ':cmd' => './%binary% -game left4dead -ip %ip% -port %port% +map %map%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'l4d',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => '',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 222860,
        ':updates' => 1,
        ':shorten' => 'left4dead2',
        ':description' => 'Left 4 Dead 2',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => '',
        ':modfolder' => 'left4dead2',
        ':fps' => null,
        ':slots' => 0,
        ':map' => 'c2m1_highway',
        ':cmd' => './%binary% -game left4dead2 -ip %ip% -port %port% +map %map% ',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'l4d2',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => '',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 17575,
        ':updates' => 1,
        ':shorten' => 'pvkii',
        ':description' => 'Pirates, Vikings, and Knights II',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => '',
        ':modfolder' => 'pvkii',
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'tw_temple',
        ':cmd' => './%binary% -game pvkii -ip %ip% -port %port% +maxplayers %slots% +map %map% +tv_port %tvport%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'source',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 17515,
        ':updates' => 1,
        ':shorten' => 'ageofchivalry',
        ':description' => 'Age Of Chivalry',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => '',
        ':modfolder' => 'ageofchivalry',
        ':fps' => 75,
        ':slots' => 12,
        ':map' => 'aoc_battleground',
        ':cmd' => './%binary% -game ageofchivalry -ip %ip% -port %port% +maxplayers %slots% +map %map% +fps_max %fps% +tv_port %tvport%',
        ':modcmds' => null,
        ':tic' => 66,
        ':gameq' => 'aoc',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 90,
        ':updates' => 1,
        ':shorten' => 'dod',
        ':description' => 'Day of Defeat',
        ':gamebinary' => 'hlds_run',
        ':gamebinaryWin' => 'hlds.exe',
        ':binarydir' => null,
        ':modfolder' => 'dod',
        ':fps' => 100,
        ':slots' => 12,
        ':map' => 'dod_anzio',
        ':cmd' => './%binary% -game dod -ip %ip% -port %port% +sys_ticrate %tic% +maxplayers %slots% +map %map% +fps_max %fps%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'dod',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 232370,
        ':updates' => 1,
        ':shorten' => 'hl2mp',
        ':description' => 'HL2 Deathmatch',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => null,
        ':modfolder' => 'hl2mp',
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'dm_lockdown',
        ':cmd' => './%binary% -game hl2mp -ip %ip% -port %port% +maxplayers %slots% +map %map% +tv_port %tvport%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'hl2dm',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 17705,
        ':updates' => 1,
        ':shorten' => 'insurgency',
        ':description' => 'Insurgency',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => null,
        ':modfolder' => 'insurgency',
        ':fps' => 100,
        ':slots' => 12,
        ':map' => 'ins_abdallah',
        ':cmd' => './%binary% -game insurgency -ip %ip% -port %port% +maxplayers %slots% +map %map% +fps_max %fps%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'insurgency',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 232250,
        ':updates' => 1,
        ':shorten' => 'tf',
        ':description' => 'Team Fortress 2',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => null,
        ':modfolder' => 'tf',
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'cp_5gorge',
        ':cmd' => './%binary% -game tf -ip %ip% -port %port% +maxplayers %slots% +map %map% +tv_port %tvport%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'tf2',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' =>  'S',
        ':appID' => 90,
        ':updates' => 1,
        ':shorten' => 'tfc',
        ':description' => 'Team Fortress Classic',
        ':gamebinary' => 'hlds_run',
        ':gamebinaryWin' => 'hlds.exe',
        ':binarydir' => null,
        ':modfolder' => 'tfc',
        ':fps' => 100,
        ':slots' => 12,
        ':map' => '2fort',
        ':cmd' => './%binary% -game tfc -ip %ip% -port %port% +sys_ticrate %tic% +maxplayers %slots% +map %map% +fps_max %fps%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'tfc',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 17505,
        ':updates' => 1,
        ':shorten' => 'zps',
        ':description' => 'Zombie Panic Source',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => null,
        ':modfolder' => 'zps',
        ':fps' => 100,
        ':slots' => 12,
        ':map' => 'zpa_badbayou',
        ':cmd' => './%binary% -game zps -ip %ip% -port %port% +maxplayers %slots% +map %map% +fps_max %fps%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'zps',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\nmaplist.txt full\r\nmapcycle.txt full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 27015,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 211820,
        ':updates' => 1,
        ':shorten' => 'starbound',
        ':description' => 'Starbound',
        ':gamebinary' => 'starbound_server',
        ':binarydir' => 'linux64',
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => '',
        ':cmd' => './%binary% -bootconfig %absolutepath%/linux64/bootstrap.config -log starbound_server.log',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'starbound',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "starbound.config",
        ':configedit' => "[linux64/bootstrap.config] json\r\n\"storageDirectory\" : \"%absolutepath%\"\r\n\r\n[starbound.config] json\r\n\"bind\" : \"%ip%\",\r\n\"maxPlayers\" : %slots%,\r\n\"gamePort\" : %port%,\r\n\"controlPort\" : %port2%,\r\n\"authPort\" : %port3%,\r\n\r\n[assets/default_configuration.config] json\r\n\"storageDirectory\" : \"%absolutepath%/\",",
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 21025,
        ':portTwo' => 21026,
        ':portThree' => 21027,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 740,
        ':updates' => 1,
        ':shorten' => 'csgo',
        ':description' => 'Counter-Strike: Global Offensive',
        ':gamebinary' => 'srcds_run',
        ':gamebinaryWin' => 'srcds.exe',
        ':binarydir' => null,
        ':modfolder' => 'csgo',
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'de_dust',
        ':cmd' => './%binary% -game csgo -console -usercon +ip %ip% +hostport %port% +tv_port %tvport% +clientport %port3% -maxplayers_override %slots% -tickrate %tickrate% +mapgroup %mapgroup% +map %map%',
        ':modcmds' => "[Classic Casual = default]\r\n+game_type 0 +game_mode 0\r\n\r\n[Classic Competitive]\r\n+game_type 0 +game_mode 1\r\n\r\n[Arms Race]\r\n+game_type 1 +game_mode 0\r\n\r\n[Demolition]\r\n+game_type 1 +game_mode 1",
        ':tic' => 66,
        ':gameq' => 'csgo',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "cfg/server.cfg both\r\ncfg/autoexec.cfg both\r\ngamemodes_server.txt\r\ncfg/server.cfg both\r\ncfg/autoexec.cfg both\r\ncfg/gamemode_armsrace.cfg\r\ncfg/gamemode_casual.cfg\r\ncfg/gamemode_competitive.cfg\r\ncfg/gamemode_custom.cfg\r\ncfg/gamemode_deathmatch.cfg\r\ncfg/gamemode_demolition.cfg\r\ncfg/gamemode_training.cfg",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 27015,
        ':portTwo' => 27016,
        ':portThree' => 27017,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => 'mg_demolition',
        ':protected' => 'Y',
        ':protectedSaveCFGs' => 'cfg/server.cfg',
        ':ramLimited' => 'N',
        ':os' => 'B'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'mc',
        ':description' => 'Minecraft',
        ':gamebinary' => 'minecraft_server.jar',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => 'java -Xmx%maxram%M -Xms%minram%M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=%maxcores% -XX:+AggressiveOpts -jar %binary% nogui',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'minecraft',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server.properties full",
        ':configedit' => "[server.properties] ini\r\nserver-port=%port%\r\nquery.port=%port%\r\nenable-query=true\r\nrcon.port=%port2%\r\nserver-ip=%ip%\r\nmax-players=%slots%",
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 25565,
        ':portTwo' => 25566,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'Y',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'bukkit',
        ':description' => 'MC Bukkit',
        ':gamebinary' => 'craftbukkit.jar',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => 'java -Xincgc -Xmx%maxram%M -Xms%minram%M -jar %binary% -o true -h %ip% -p %port% -s %slots% --log-append false --log-limit 50000',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'minecraft',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server.properties full",
        ':configedit' => "[server.properties] ini\r\nserver-port=%port%\r\nquery.port=%port%\r\nenable-query=true\r\nrcon.port=%port2%\r\nserver-ip=%ip%\r\nmax-players=%slots%",
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 25565,
        ':portTwo' => 25566,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'Y',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'tekkit',
        ':description' => 'MC Tekkit',
        ':gamebinary' => 'Tekkit.jar',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => 'java -Xincgc -Xmx%maxram%M -Xms%minram%M -jar %binary% -o true -h %ip% -p %port% -s %slots% --log-append false --log-limit 50000',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'minecraft',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server.properties full",
        ':configedit' => "[server.properties] ini\r\nserver-port=%port%\r\nquery.port=%port%\r\nenable-query=true\r\nrcon.port=%port2%\r\nserver-ip=%ip%\r\nmax-players=%slots%",
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 25565,
        ':portTwo' => 25566,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'Y',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'tekkit-classic',
        ':description' => 'MC Tekkit Classic',
        ':gamebinary' => 'Tekkit.jar',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => 'java -Xincgc -Xmx%maxram%M -Xms%minram%M -jar %binary% -o true -h %ip% -p %port% -s %slots% --log-append false --log-limit 50000',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'minecraft',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server.properties full",
        ':configedit' => "[server.properties] ini\r\nserver-port=%port%\r\nquery.port=%port%\r\nenable-query=true\r\nrcon.port=%port2%\r\nserver-ip=%ip%\r\nmax-players=%slots%",
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 25565,
        ':portTwo' => 25566,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'Y',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'samp',
        ':description' => 'GTA San Andreas',
        ':gamebinary' => 'samp03svr',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => './%binary%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'samp',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server.cfg both",
        ':configedit' => "[server.cfg] cfg\r\nmaxplayers %slots%\r\nport %port%",
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 7777,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'mtasa',
        ':description' => 'Multi Theft Auto San Andreas',
        ':gamebinary' => 'mta-server',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => './%binary%',
        ':modcmds' => "[mods/deathmatch/mtaserver.conf] xml\r\n<serverip>%ip%</serverip>\r\n<serverport>%port%</serverport> \r\n<httpport>%port2%</httpport>\r\n<maxplayers>%slots%</maxplayers>\r\n<httpserver>0</httpserver>",
        ':tic' => null,
        ':gameq' => 'Mta',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "mods/deathmatch/mtaserver.conf full",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 22003,
        ':portTwo' => 22005,
        ':portThree' => 22126,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'teeworlds',
        ':description' => 'Teeworlds',
        ':gamebinary' => 'teeworlds_srv',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => './%binary%',
        ':modcmds' => "[Capture the Flag = default]\r\n-f config_ctf.cfg\r\n\r\n[Deathmatch]\r\n-f config_dm.cfg\r\n\r\n[Team Deathmatch]\r\n-f config_tdm.cfg",
        ':tic' => null,
        ':gameq' => 'teeworlds',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "config_ctf.cfg\r\nconfig_dm.cfg\r\nconfig_tdm.cfg",
        ':configedit' => "[autoexec.cfg] cfg\r\nsv_max_clients %slots%\r\nbindaddr %ip%\r\nsv_bindaddr %ip%\r\nsv_port %port%\r\n\r\n[config_ctf.cfg] cfg\r\nsv_max_clients %slots%\r\nbindaddr %ip%\r\nsv_bindaddr %ip%\r\nsv_port %port%\r\n\r\n[config_dm.cfg] cfg\r\nsv_max_clients %slots%\r\nbindaddr %ip%\r\nsv_bindaddr %ip%\r\nsv_port %port%\r\n\r\n[config_tdm.cfg] cfg\r\nsv_max_clients %slots%\r\nbindaddr %ip%\r\nsv_bindaddr %ip%\r\nsv_port %port%",
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 8303,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => '',
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'killingfloor252',
        ':description' => 'KillingFloor 2.52',
        ':gamebinary' => 'ucc-bin',
        ':binarydir' => 'System',
        ':modfolder' => 'KFMod20',
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'KF-Offices.ut2',
        ':cmd' => './%binary% server KF-Offices?game=KFMod.KFGameType?GameStats=True?MaxPlayers=%slots% -mod="KFMod20" -log=../Logs/KF_Server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'killingfloor',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "KFMod20/System/KFMod20.ini",
        ':configedit' => "[autoexec.cfg] cfg\r\nsv_max_clients %slots%\r\nsv_bindaddr %ip%\r\nsv_port %port%\r\n\r\n[config_ctf.cfg] cfg\r\nsv_max_clients %slots%\r\nsv_bindaddr %ip%\r\nsv_port %port%\r\n\r\n[config_dm.cfg] cfg\r\nsv_max_clients %slots%\r\nsv_bindaddr %ip%\r\nsv_port %port%\r\n\r\n[config_tdm.cfg] cfg\r\nsv_max_clients %slots%\r\nsv_bindaddr %ip%\r\nsv_port %port%",
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 7777,
        ':portTwo' => 7787,
        ':portThree' => 7778,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'sauerbratenremod',
        ':description' => 'Sauerbraten',
        ':gamebinary' => 'remod',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => './%binary% -i%ip% -j%port% -c%slots% -fserver-init.cfg',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'cube2',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "server-init.cfg full",
        ':configedit' => "[server-init.cfg] cfg\r\nserverip \"%ip%\"\r\nserverport \"%port%\"\r\nmaxclients \"%slots%\"",
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 28785,
        ':portTwo' => 28786,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'shootmania',
        ':description' => 'Shootmania',
        ':gamebinary' => 'ShootmaniaServer.sh',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'ShootmaniaServer',
        ':cmd' => './%binary% /dedicated_cfg=dedicated_cfg.txt /nodaemon /bindip=%ip% /forceip=%ip%',
        ':modcmds' => "[Shootmania Combo]\r\n/game_settings=MatchSettings/Combo.txt /title=SMStormCombo@nadeolabs\r\n\r\n[Shootmania Battle]\r\n/game_settings=MatchSettings/Battle.txt /title=SMStorm\r\n\r\n[Shootmania Elite = default]\r\n/game_settings=MatchSettings/Elite.txt /title=SMStormElite@nadeolabs\r\n\r\n[Shootmania Heroes]\r\n/game_settings=MatchSettings/Hereos.txt /title=SMStormHeroes@nadeolabs\r\n\r\n[Shootmania Joust]\r\n/game_settings=MatchSettings/Joust.txt /title=SMStormJoust@nadeolabs\r\n\r\n[Shootmania Melee]\r\n/game_settings=MatchSettings/Melee.txt /title=SMStorm\r\n\r\n[Shootmania Realms / broken]\r\n/game_settings=MatchSettings/Realms.txt /title=SMStorm\r\n\r\n[Shootmania Royal]\r\n/game_settings=MatchSettings/Royal.txt /title=SMStormRoyal@nadeolabs\r\n\r\n[Shootmania Siege]\r\n/game_settings=MatchSettings/Siege.txt /title=SMStorm\r\n\r\n[Shootmania TimeAttack / broken]\r\n/game_settings=MatchSettings/TimeAttack.txt /title=SMStorm\r\n\r\n[Shootmania YOUR Mod, ask the Support]\r\n/game_settings=MatchSettings/CustomMod.txt",
        ':tic' => null,
        ':gameq' => '',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "UserData/Config/dedicated_cfg.txt\r\nUserData/Maps/MatchSettings/Battle.txt\r\nUserData/Maps/MatchSettings/Elite.txt\r\nUserData/Maps/MatchSettings/Hereos.txt\r\nUserData/Maps/MatchSettings/Joust.txt\r\nUserData/Maps/MatchSettings/Melee.txt\r\nUserData/Maps/MatchSettings/Realms.txt\r\nUserData/Maps/MatchSettings/Royal.txt\r\nUserData/Maps/MatchSettings/Siege.txt\r\nUserData/Maps/MatchSettings/TimeAttack.txt\r\nUserData/Maps/MatchSettings/CustomMod.txt",
        ':configedit' => "[UserData/Config/dedicated_cfg.txt] xml\r\n<max_players>%slots%</max_players>\r\n<max_spectators>10</max_spectators>\r\n<enable_p2p_upload>false</enable_p2p_upload>\r\n<connection_uploadrate>2048</connection_uploadrate>\r\n<connection_downloadrate>4096</connection_downloadrate>\r\n<force_ip_address>%ip%</force_ip_address>\r\n<server_port>%port%</server_port>\r\n<server_p2p_port>%port2%</server_p2p_port>\r\n<bind_ip_address>%ip%</bind_ip_address>\r\n<xmlrpc_port>%port3%</xmlrpc_port>",
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 2350,
        ':portTwo' => 2351,
        ':portThree' => 2352,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'trackmania',
        ':description' => 'Trackmania2',
        ':gamebinary' => 'TrackmaniaServer.sh',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'TrackmaniaServer',
        ':cmd' => './%binary% /dedicated_cfg=dedicated_cfg.txt /nodaemon /bindip=%ip% /forceip=%ip%',
        ':modcmds' => "[Trackmania2 Canyon A = default]\r\n/game_settings=MatchSettings/TMCanyonA.txt /title=TMCanyon\r\n\r\n[Trackmania2 Canyon B]\r\n/game_settings=MatchSettings/TMCanyonB.txt /title=TMCanyon\r\n\r\n[Trackmania2 Canyon C]\r\n/game_settings=MatchSettings/TMCanyonC.txt /title=TMCanyon\r\n\r\n[Trackmania2 Canyon Custom]\r\n/game_settings=MatchSettings/TMCanyonCustom.txt /title=TMCanyon\r\n\r\n[Trackmania2 Stadium A]\r\n/game_settings=MatchSettings/TMStadiumA.txt /title=TMStadium\r\n\r\n[Trackmania2 Stadium B]\r\n/game_settings=MatchSettings/TMStadiumB.txt /title=TMStadium\r\n\r\n[Trackmania2 Stadium C]\r\n/game_settings=MatchSettings/TMStadiumC.txt /title=TMStadium\r\n\r\n[Trackmania2 Stadium Custom]\r\n/game_settings=MatchSettings/TMStadiumCustom.txt /title=TMStadium\r\n\r\n[Trackmania2 Valley A]\r\n/game_settings=MatchSettings/TMValleyA.txt /title=TMValley\r\n\r\n[Trackmania2 Valley B]\r\n/game_settings=MatchSettings/TMValleyB.txt /title=TMValley\r\n\r\n[Trackmania2 Valley C]\r\n/game_settings=MatchSettings/TMValleyC.txt /title=TMValley\r\n\r\n[Trackmania2 Valley Custom]\r\n/game_settings=MatchSettings/TMValleyCustom.txt /title=TMValley\r\n\r\n[Trackmania2 Platform A]\r\n/game_settings=MatchSettings/CanyonPlatformA.txt /title=Platform@nadeolive\r\n\r\n[Trackmania2 Platform B]\r\n/game_settings=MatchSettings/CanyonPlatformB.txt /title=Platform@nadeolive\r\n\r\n[Trackmania2 Platform C]\r\n/game_settings=MatchSettings/CanyonPlatformC.txt /title=Platform@nadeolive\r\n\r\n[Trackmania2 Platform Custom]\r\n/game_settings=MatchSettings/CanyonPlatformCustom.txt /title=Platform@nadeolive",
        ':tic' => null,
        ':gameq' => '',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "UserData/Config/dedicated_cfg.txt\r\nUserData/Maps/MatchSettings/TMCanyonCustom.txt\r\nUserData/Maps/MatchSettings/TMStadiumCustom.txt\r\nUserData/Maps/MatchSettings/TMValleyCustom.txt\r\nUserData/Maps/MatchSettings/CanyonPlatformCustom.txt",
        ':configedit' => "[UserData/Config/dedicated_cfg.txt] xml\r\n<max_players>%slots%</max_players>\r\n<max_spectators>10</max_spectators>\r\n<enable_p2p_upload>false</enable_p2p_upload>\r\n<connection_uploadrate>2048</connection_uploadrate>\r\n<connection_downloadrate>4096</connection_downloadrate>\r\n<force_ip_address>%ip%</force_ip_address>\r\n<server_port>%port%</server_port>\r\n<server_p2p_port>%port2%</server_p2p_port>\r\n<bind_ip_address>%ip%</bind_ip_address>\r\n<xmlrpc_port>%port3%</xmlrpc_port>",
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 2350,
        ':portTwo' => 2351,
        ':portThree' => 2352,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'ut99',
        ':description' => 'Unreal Tournament',
        ':gamebinary' => 'ucc-bin',
        ':binarydir' => 'System',
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'DM-Codex.unr',
        ':cmd' => './%binary% server',
        ':modcmds' => "[DM = default]\r\n%map%?Game=Botpack.DeathMatchPlus?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[TDM]\r\n%map%?Game=Botpack.TeamGamePlus?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[CTF]\r\n%map%?Game=Botpack.CTFGame?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[LMS]\r\n%map%?Game=Botpack.LastManStanding?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[DOM]\r\n%map%?Game=Botpack.Domination?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[BT]\r\n%map%?Game=BunnyTrack.BunnyTrackGame?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[JB]\r\n%map%?Game=JailBreak.JailBreak?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[MH]\r\n%map%?Game=Monsterhunt.Monsterhunt?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[TMH]\r\n%map%?Game=TeamMH.TeamMH?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[RA]\r\n%map%?Game=RocketArena.ArenaGame?MaxPlayers=%slots% -ini=UnrealTournament.ini -log=server.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir",
        ':tic' => null,
        ':gameq' => 'ut',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "ReadMe_WebAdmin_AdminPassword_ReDirect.txt",
        ':configedit' => null,
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 7777,
        ':portTwo' => 7778,
        ':portThree' => 7779,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'ut2004',
        ':description' => 'UT2004',
        ':gamebinary' => 'ucc-bin',
        ':binarydir' => 'System',
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => 'DM-Rankin.ut2',
        ':cmd' => './%binary% server',
        ':modcmds' => "[DM = default]\r\n%map%?Game=XGame.xDeathMatch?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[TDM]\r\n%map%?Game=XGame.xTeamGame?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[CTF]\r\n%map%?Game=XGame.xCTFGame?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[iCTF-Clan]\r\n%map%?Game=XGame.InstagibCTF?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[iCTF-Public]\r\n%map%?Game=XGame.xCTFGame?Mutator=XGame.MutInstaGib?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[TAM]\r\n%map%?Game=3spnv3141.TeamArenaMaster?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[AM]\r\n%map%?Game=3spnv3141.ArenaMaster=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[Freon]\r\n%map%?Game=3SPNv3141.Freon?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[ONS]\r\n%map%?Game=Onslaught.ONSOnslaughtGame?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[LMS]\r\n%map%?Game=BonusPack.xLastManStandingGame?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[DDOM]\r\n%map%?Game=XGame.xDoubleDom?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[BR]\r\n%map%?Game=XGame.xBombingRun?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[vCTF]\r\n%map%?Game=XGame.xVehicleCTFGame?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[Mutant]\r\n%map%?Game=BonusPack.xMutantGame?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[SkaarjPack.Invasion]\r\n%map%?Game=SkaarjPack.Invasion?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[AS]\r\n%map%?Game=UT2K4Assault.ASGameInfo?MaxPlayers=%slots% -ini=UT2004.ini -log=UT2004.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir\r\n\r\n[Jailbreak]\r\n%map%?Game=Jailbreak.Jailbreak?MaxPlayers=%slots% -ini=UT2004_JB.ini -log=UT2004_JB.log -multihome=%ip% -port=%port% -queryport=%port2% -WebServerListenPort=%port3% -nohomedir",
        ':tic' => null,
        ':gameq' => 'ut2004',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "System/UT2004.ini\r\nSystem/XAdmin.ini\r\nReadMe_WebAdmin_AdminPassword_ReDirect.txt",
        ':configedit' => "[System/UT2004.ini] ini\r\nListenPort=%port3%",
        ':portStep' => 10,
        ':portMax' => 3,
        ':portOne' => 7777,
        ':portTwo' => 7778,
        ':portThree' => 7779,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'N',
        ':appID' => null,
        ':updates' => 1,
        ':shorten' => 'warsow',
        ':description' => 'WarSow',
        ':gamebinary' => 'wsw_server.x86_64',
        ':binarydir' => '',
        ':modfolder' => 'basewsw',
        ':fps' => null,
        ':slots' => 12,
        ':map' => '',
        ':cmd' => './%binary% +exec dedicated_server.cfg +set sv_maxclients %slots% +set sv_ip %ip% +set sv_port %port% +set sv_port6 %port%',
        ':modcmds' => "[Deathmatch]\r\n+set g_gametype \"dm\"\r\n\r\n[Team Deathmatch]\r\n+set g_gametype \"tdm\"\r\n\r\n[Team DMCTF]\r\n+set g_gametype \"tdm_ctf\"\r\n\r\n[Capture the Flag]\r\n+set g_gametype \"ctf\"\r\n\r\n[Clan Arena]\r\n+set g_gametype \"ca\"\r\n\r\n[Duel]\r\n+set g_gametype \"duel\"\r\n\r\n[Duel Arena]\r\n+set g_gametype \"da\"\r\n\r\n[DuelQuad]\r\n+set g_gametype \"duel_quad\"\r\n\r\n[FFA = default]\r\n+set g_gametype \"ffa\"\r\n\r\n[Mid Air]\r\n+set g_gametype \"midair\"\r\n\r\n[Race]\r\n+set g_gametype \"race\"\r\n\r\n[All Round]\r\n+set g_gametype \"allaround\"",
        ':tic' => null,
        ':gameq' => 'warsow',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "basewsw/dedicated_server.cfg\r\nbasewsw/motd.cfg",
        ':configedit' => "[basewsw/dedicated_autoexec.cfg] cfg\r\nsv_ip \"%ip%\"\r\nsv_port \"%port%\"\r\nsv_port6 \"%port%\"\r\nsv_maxclients \"%slots%\"",
        ':portStep' => 10,
        ':portMax' => 1,
        ':portOne' => 44400,
        ':portTwo' => null,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    ),
    array(
        ':steamgame' => 'S',
        ':appID' => 261140,
        ':updates' => 1,
        ':shorten' => 'jc2',
        ':description' => 'Just Cause 2 Multi Player',
        ':gamebinary' => 'Jcmp-Server',
        ':binarydir' => null,
        ':modfolder' => null,
        ':fps' => null,
        ':slots' => 12,
        ':map' => null,
        ':cmd' => './%binary%',
        ':modcmds' => null,
        ':tic' => null,
        ':gameq' => 'jcmp',
        ':gamemod' => 'N',
        ':gamemod2' => null,
        ':configs' => "config.lua",
        ':configedit' => "[config.lua] lua\r\nMaxPlayers = %slots%,\r\nBindIP = \"%ip%\",\r\nBindPort = %port%,",
        ':portStep' => 10,
        ':portMax' => 2,
        ':portOne' => 28785,
        ':portTwo' => 28786,
        ':portThree' => null,
        ':portFour' => null,
        ':portFive' => null,
        ':mapGroup' => null,
        ':protected' => 'N',
        ':protectedSaveCFGs' => null,
        ':ramLimited' => 'N',
        ':os' => 'L'
    )
);